import { Router } from "express";
import { addDelivery, addReceipt, createRepresentative, deleteRepresentative, deliverPartial, getAccount, getDelivery, getRepresentative, listRepresentatives, removeDelivery, updateDelivery, updateReceipt, deleteReceipt, updateRepresentative } from "../controllers/representativeController.js";
import { authorize, permit } from "../middleware/authenticate.js";
const router = Router();
router.get("/", listRepresentatives);
router.post("/", permit("representatives.manage", "administrator", "manager"), createRepresentative);
router.get("/:id", getRepresentative);
router.get("/:id/account", getAccount);
router.get("/:id/deliveries/:deliveryId", getDelivery);
router.put("/:id", permit("representatives.manage", "administrator", "manager"), updateRepresentative);
router.delete("/:id", permit("representatives.manage", "administrator", "manager"), deleteRepresentative);
router.post("/:id/receipts", permit("representatives.manage", "administrator", "manager"), addReceipt);
router.put("/:id/receipts/:receiptId", permit("representatives.manage", "administrator", "manager"), updateReceipt);
router.delete("/:id/receipts/:receiptId", permit("representatives.manage", "administrator", "manager"), deleteReceipt);
router.post("/:id/deliveries", permit("representatives.manage", "administrator", "manager"), addDelivery);
router.put("/:id/deliveries/:deliveryId", permit("representatives.manage", "administrator", "manager"), updateDelivery);
router.post("/:id/deliveries/:deliveryId/deliver", permit("representatives.manage", "administrator", "manager"), deliverPartial);
router.delete("/:id/deliveries/:deliveryId", permit("representatives.manage", "administrator", "manager"), removeDelivery);
export default router;
